name: Build

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: ./

    - name: Add Dependency File
      run: |
        mkdir -p artifact/QuestionBank
        cp -r dist/windows/* artifact/
        cp -r QuestionBank/* artifact/QuestionBank/
        cp ai.conf artifact/

    - uses: actions/upload-artifact@v4
      with:
        name: weiban-tool
        path: artifact/